name: Charts Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Helm
        run: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            chmod 700 get_helm.sh
            sudo ./get_helm.sh
      - name: Run Script
        run: |
          ./.github/scripts/publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}